#!/bin/sh

# How to generate this script:
# :l test/BigTest.hs
# mapM_ print [Params 1000 1000 False "/home/eamybut/mnist/trainingData/" "/home/eamybut/mnist/testData/" 0.1 0.005 cdtX 60000 0.1 0.005 0.1 [-0.01, -0.01, -0.01, -0.01] 1 | cdtX <- [0.06, 0.07, 0.08, 0.11]]

# DO NOT DELETE
cd ~/néal/numeral-wains/spectrum
# DO NOT DELETE

# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 5.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 4.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 3.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 2.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log

# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 6.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 7.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 8.0e-2, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
# rm -f superwain; /home/eamybut/nosync/sandboxes/numeral-wains/bin/mnist-big-test 'Params {nTrainingImages = 1000, nTestImages = 1000, reportNovelty = False, trainingDir = "/home/eamybut/mnist/trainingData/", testDir = "/home/eamybut/mnist/testData/", cr0 = 0.1, cDecay = 5.0e-3, cdt = 0.11, cSize = 1000, pr0 = 0.1, pDecay = 5.0e-3, pdt = 0.1, defO = [-1.0e-2,-1.0e-2,-1.0e-2,-1.0e-2], depth = 1}' >> spectrum.log
